### PR TITLE
chore: fix Windows builds + upgrade esy

### PR DESCRIPTION
**Pull request by ManasJayanth**

### CODE REVIEW

**Comment by ManasJayanth** [comment]
@dmtrKovalenko Is there way to retrigger the Linux job? The error seems like a network issue.

**Comment by dmtrKovalenko** [comment]
Not sure if you can use it but there is a button 
image

**Comment by ManasJayanth** [comment]
@dmtrKovalenko Green CI! Hope this helped.

**Review by dmtrKovalenko — APPROVED** [review]

**Comment by dmtrKovalenko** [comment]
Thank you for this help! But can you please elaborate ab bit on what actually did you do and why the title says "windows support". I think windows build did work before as well, aren't they?

**Comment by ManasJayanth** [comment]
> I think windows build did work before as well, aren't they?

CI was red. And locally it never built for me because,
1. esy's pnp.js file out of sync
2. Broken packages

The new `beta` release fixes the above two. I have update the broken native packages to use package formulaes I wrote (and will hopefully get time to maintain)

CI was also on an old version of Node.js

**Comment by ManasJayanth** [comment]
> I can't see anything specific to windows support here https://github.com/esy/esy/releases/tag/v0.6.14

I'm using the latest beta, 0.7.0-beta.3 which contains pnp fixes and support for long paths on Windows. Long paths shouldn't be a problem for this project, but is a concern for some large projects (tezos and ligo). Changelog for 0.7.0 beta was autogenerated. I plan to hand-write one before the final release.

**Comment by ManasJayanth** [comment]
You can find the beta pre-releases of esy here: https://github.com/esy/esy/releases

**Comment by dmtrKovalenko** [comment]
Ok thank you for clarification!

**Pull request merged**
