### PR TITLE
Fix comparison when layout differs

### PR DESCRIPTION
**Pull request by serpent7776**
In case `layoutDifference` is `true` `compColor` is assigned incorrect pixel value read from `base` instead of `comp`.

### CODE REVIEW

**Review by dmtrKovalenko — APPROVED** [review]

**Comment by dmtrKovalenko** [comment]
It would be amazing if you can add a test case that would fail with the previous implementation

**Comment by serpent7776** [comment]
I have no idea how to add new image files, because they are not being copied to the `_build` dir by dune.

**Comment by dmtrKovalenko** [comment]
intersting we have one of the existing tests failing could you please elaborate more on why do you think the existing test is wrong

**Comment by serpent7776** [comment]
I can understand that current value of `399` comes from difference in the image sizes, but now there's `18` more pixels. I don't know how antialiased comparison works, so I don't know why.

**Comment by serpent7776** [comment]
The following pixels are considered different (where previously weren't) after this fix:

```
x,y
90,0
93,0
94,0
95,0
96,0
103,0
104,0
105,0
106,0
109,0
0,90
0,93
0,95
0,96
0,103
0,104
0,106
0,109
```

**Comment by serpent7776** [comment]
I added a new test. Locally I had to copy the new images manually to `_build` directory for whatever reason.

**Comment by serpent7776** [comment]
I updated expects for the failing test :shrug:

**Pull request merged**
