### PR TITLE
increase performance of color checks

### PR DESCRIPTION
**Pull request by eWert-Online**
This removes the `isSameColor` helper function and replaces it with a simple equality check on the two tuples.
In my tests this increased the performance of the 4k-water image by roughly 300ms.

I also cleaned up some of the antialiasing code. These are just cosmetic changes though 🙂

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Hmmmmmmm when I have tested this comparing 2 tuples was slower than comparing each content one by one. Because OCaml is doing additional checks for tuple length, types in runtime. I am surprised that this is faster. 

Maybe it gots deoptimised because moved to separate module? But I was expecting this to be inlined by flambda.

And one more simple question – what do you think about moving to same architecture as you have done for BigArrrays? Return int32 for pixel, comparing this int32 which must be much faster and then decode it to the rgba int8? It looks like the best solution because usually images contain much more identical pixels

**Comment by eWert-Online** [comment]
> Hmmmmmmm when I have tested this comparing 2 tuples was slower than comparing each content one by one. Because OCaml is doing additional checks for tuple length, types in runtime. I am surprised that this is faster.

It does generate a lot less cpu instructions though, so to me it made sense, that it was faster. 
But maybe it was just the fact, that it is inlined now and maybe not before.

> Maybe it gots deoptimised because moved to separate module? But I was expecting this to be inlined by flambda.

As far as I can see, we currently aren't compiling with flambda optimizations enabled. `esy ocamlopt -config` says `flambda: false`. 
This is also something I maybe wanted to take a look at. Also maybe updating to 4.12 while we are at it.

> And one more simple question – what do you think about moving to same architecture as you have done for BigArrrays? Return int32 for pixel, comparing this int32 which must be much faster and then decode it to the rgba int8?

Yes, that is a good idea! I think it isn't guaranteed that it is faster though, as Int32 operations are a lot slower than operations on int. But I will definitely take a look at it.

**Comment by eWert-Online** [comment]
Yeah...so...it did increase the performance 😄 

diff

**Comment by dmtrKovalenko** [comment]
cool, but I thought it will require changes to ReadPng.c where we allocate big array as UINT8 type

**Comment by dmtrKovalenko** [comment]
I mean here https://github.com/dmtrKovalenko/odiff/blob/cleanup/io/ReadPng.c#L155 big array is still allocated as UINT8 type

**Comment by eWert-Online** [comment]
Good point 🙂 I updated it to int32.
I also changed the pixel layout to be `abgr`, as that is the format we are getting back from readpng. So we now don't have to shift around the bits anymore.

**Review by dmtrKovalenko — APPROVED** [review]

**Pull request merged**
