### PR TITLE
CI: Use Ubuntu 18.04

### PR DESCRIPTION
**Pull request by ManasJayanth**

### CODE REVIEW

**Comment by ManasJayanth** [comment]
@dmtrKovalenko I dont have the restart/re-run button available here. Can you try restarting the Linux job again?

**Comment by dmtrKovalenko** [comment]
I have never seen such timeout errors before, same situation in main as well. Do you think this might be related to your changes? Or just reduced resources for free projects on azure?

**Comment by ManasJayanth** [comment]
Screenshot 2023-08-24 at 8 15 58 PM


CI network error again

**Comment by dmtrKovalenko** [comment]
btw are your resolving this issue now? https://github.com/dmtrKovalenko/odiff/actions/runs/5960944753/job/16170069182

**Comment by dmtrKovalenko** [comment]
Seems to be passed. I have another question: @ManasJayanth are you able to build this version on m1? Because I don’t. 

Unfortunately to work on odiff I need to run the docker container, you mentioned that you was not being able to build it initially — it means that you are able to build it on m1 now?

**Comment by ManasJayanth** [comment]
Yes, I have been able to build it on M1 without docker. Have you tried it with the latest beta release?

**Pull request merged**
