### PR TITLE
Cleanup & optimize performance of IO (switch to libspng)

### PR DESCRIPTION
**Pull request by eWert-Online**
This PR is an effort to switch from `libpng` to `libspng`. 
This doubles the performance of `tiff`, `bmp` and `jpg` (probably `webp` and `avif` too).

The performance of `png` sadly drops by ~200ms (edit: ~100ms).
This is because the encoder of `libspng` runs much faster compared to `libpng` when given a single byte array.
Because png was the only format which didn't use the bigarray, but the row pointers, it now is a bit slower.

The encoder of `libspng` is not yet released officially, so maybe there are also some pending performance optimizations... 😄

Using `libspng` also reduced the binary size by ~100kb.
In the future, we could also think about using `miniz` instead of `zlib`. It is also lighter and in some cases faster than zlib.

The big advantage that we get with this rewrite, is that all io implementations now use a bigarray to store and read their data. (Also we only have 1 PNG implementation now instead of 2).
So implementing something like #53 will probably get a bit easier.
We could also think about giving ocaml / reasonml users (me 😄 ) the ability to get the raw bigarray data out of the io functors.

@dmtrKovalenko What do you think? 

### Todo

- [x] cross platform tests (windows and linux)

### Performance Benchmarks

**BMP:**
benchmark-bmp

**JPG / JPEG**
benchmark-jpg

**PNG** 😞 
benchmark-png

**TIFF**
benchmark-tiff

### CODE REVIEW

**Comment by eWert-Online** [comment]
@dmtrKovalenko  Do you have any clue, why the windows pipeline gets an `EACCES` error?

**Comment by dmtrKovalenko** [comment]
I'll spend some time on weekend with this

**Comment by dmtrKovalenko** [comment]
Thanks for this, but I want to understand how having 1 implementation will help in this case? 

> So implementing something like #53 will probably get a bit easier.

Actually this type of lib where we are fighting for performance having optimizations like using raw pointers data without any data copying makes sense.

**Comment by eWert-Online** [comment]
I just realized that I had an error in my thought process.
I thought we could just dump the data given from the buffer directly into the bigarray. Now I realize, that we still have to run it trough the decoder of the given type 🤦
So we could still use raw pointers in theory.

I still think lib**s**png is an optimization over libpng in terms of speed though.
If the drop of ~100ms is your only concern with this PR, I think there are still some perfomance gains on the table I didn't yet explore, because I wasn't sure if you would be open to this change in general.

**Comment by dmtrKovalenko** [comment]
Yeah I think that we can merge it but left 2 different decoders only for benchmarks 🙈

**Comment by eWert-Online** [comment]
> Yeah I think that we can merge it but left 2 different decoders only for benchmarks
I am not sure I understand this correctly. You want to have libpng and libspng at the same time?

**Comment by dmtrKovalenko** [comment]
Oh my gosh yeah that is not an option -__-  I`ll get back to this code in a few hours with more fresh mind to figure everything out

**Comment by eWert-Online** [comment]
Well...let me first take a look, if I can optimize the performance of the PNG IO a bit further.
Maybe even making it faster than the one we had before 🙂 
Currently decoding and encoding with lib**s**png is faster than with libpng. The only thing slowing us down is that we are reading from ocamls bigarray with all its boxed data.

**Comment by ManasJayanth** [comment]
re: Windows
Can someone try this nightly build and let me know if it still fails? 
0.6.11-19279b

https://www.npmjs.com/package/@esy-nightly/esy/v/0.6.11-19279b

**Comment by dmtrKovalenko** [comment]
@ManasJayanth  doesn't work https://dev.azure.com/dmtrkovalenko/odiff/_build/results?buildId=285&view=results basically get back to downloading esy@nightly [here](https://github.com/dmtrKovalenko/odiff/pull/58)

**Comment by ManasJayanth** [comment]
@dmtrKovalenko In the build logs you linked, I don't think it's using the nightly I suggested. Am I missing something?

**Comment by eWert-Online** [comment]
@dmtrKovalenko 
I made soma adjustments. I mainly moved from a double nested for-loop for the x and y axis to a single loop.
We now have equal performance for png with the main branch:

diff
(main is the first one)

We are currently still incrementing x and y. 
If I am not mistaken though, I think we can compute everything from the loop offset. Definetly something I want to investigate in the future.

**Comment by eWert-Online** [comment]
@dmtrKovalenko 
Did you find time to look at this yet? 🙂 
Is this approach something you could imagine moving forward with?

**Comment by dmtrKovalenko** [comment]
Sorry for so long delay, I had pretty busy period several months. I will take a look and merge this PR until the end of this week.

Honestly, I Was scared on the amount of code to read (the new deps) 😔

**Review by dmtrKovalenko — APPROVED** [review]
Thanks! Once again I am sorry for so long review

**Pull request merged**
