### PR TITLE
Link to static libpng.a (#41)

### LINKED ISSUE #41: Cannot compare images - Library not loaded, image not found
not sure why it's not working

here is the repo to reproduce
https://github.com/pashidlos/image-compare-tryouts/blob/main/src/odiff.js

`node src/odiff.js`

```js
(node:24395) UnhandledPromiseRejectionWarning: Error: dyld: Library not loaded: _____________________________________________________________________________________/i/esy_libpng-635d6ecc/lib/libpng16.16.dylib
  Referenced from: /Users/pashidlos/work/image-compare-try/node_modules/odiff-bin/3/i/odiff-4d94fb12/bin/ODiffBin
  Reason: image not found
```

### PR DESCRIPTION
**Pull request by eWert-Online**
This is an effort to link to the static `libpng.a` instead of the `libpng.so`.

**Currently this breaks the camlimages io, because I needed to remove the `camlimages.png` lib to remove the `-lpng` flag from the linker.**  (Comparison still works fine, just saving the diff image did depend on png)

I have tested it on linux (ubuntu) and macOS. I still need to verify, that it works on Windows.

After I have got it working on windows, we need to discuss a way to get the support for `jpg, bmp, tiff and xpm` back.
The most straight forward way would be to fork camlimages and remove the `-lpng` flag.
Another way would be to not depend on `camlimages.png` and find another way to generate the diff image. 

Fixes #41

### CODE REVIEW

**Comment by eWert-Online** [comment]
@dmtrKovalenko 
libpng works on all Platforms now (MacOS, Windows and Linux).

Do you have a preference or another idea how to get back the support for the other image types?

**Comment by dmtrKovalenko** [comment]
I have no preference of how to support them, maybe even libimage or forked camlimages will work fine. 

We just need to make sure that version will be 3.0 if there is a breaking change

**Comment by eWert-Online** [comment]
Just breaking changes for the node-api or also for the reason / ocaml api?

**Comment by dmtrKovalenko** [comment]
I don't think we have a public OCaml api yet, my bad completely but yeah if we won't support global deps for libpng/libjpg we need to make a major release but it makes sense completely

**Comment by eWert-Online** [comment]
Pretty positive, that this works now 🎉 
...without breaking changes!

**Comment by dmtrKovalenko** [comment]
Wow that is awesome! Thanks @eWert-Online 
I will do some testing later today and we probably can release – **this is huge**

**Comment by dmtrKovalenko** [comment]
Hmm I notice some issues with build steps 
1) Release does not contain all the required artifacts anymore. We need to provide binaries for odiff esy-libpng and esy-zlib with release in order to link them – but now only odiff provided as _exports https://dev.azure.com/dmtrkovalenko/odiff/_build/results?buildId=242&view=artifacts&pathAsName=false&type=publishedArtifacts

2) Comparison time is 3 times bigger in comparison with main which is pretty weird it looks like it fallbacks to the system -lpng 

This branch:
Screenshot 2021-06-16 at 20 27 45

Main: 
Screenshot 2021-06-16 at 20 26 49

**Comment by dmtrKovalenko** [comment]
Ok I investigated some things and realised that libs are statically linked inside the odiff binary and that's OK but we need to figure out why so much time difference 

In main we have correctly linked libs
```
otool -L /Users/dmitrijkovalenko/dev/odiff/_release/3/i/odiff-9a5b7f55/bin/ODiffBin
/Users/dmitrijkovalenko/dev/odiff/_release/3/i/odiff-9a5b7f55/bin/ODiffBin:
        _____________________________________________________________________________________/i/esy_libpng-635d6ecc/lib/libpng16.16.dylib (compatibility version 54.0.0, current version 54.0.0)
        _____________________________________________________________________________________/i/esy_zlib-b9f35f3c/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
        /usr/local/opt/libtiff/lib/libtiff.5.dylib (compatibility version 13.0.0, current version 13.0.0)
        /usr/local/opt/jpeg/lib/libjpeg.9.dylib (compatibility version 14.0.0, current version 14.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```

**Review by dmtrKovalenko — CHANGES_REQUESTED** [review]
TODO: investigate performance degradation

**Comment by eWert-Online** [comment]
Thats indeed weird.
Maybe its because we are not using your zlib fork anymore? 🤔

I will see, if I can investigate what is going on tomorrow.

**Comment by eWert-Online** [comment]
I did find the issue.
Both `esy-libpng` and `esy-zlib` did not have optimizations turned on. 

In the currently published version of odiff, this doesn't make any difference, because we are using the globally installed ones, which are compiled with optimizations.
Now, that both libs were linked into odiff, it did use the (unoptimized) versions we provided.

I now turned `-O2` on for both libraries.
This results in the new (static) version being even faster than the currently published one, by around 400ms:

diff
_(And this is without the performance optimizations to the color checks)_

**Comment by eWert-Online** [comment]
Urghhh....Windows...

**Comment by eWert-Online** [comment]
Windows is now also working 😄 

I merged the changes from master into this branch. So now we also have the color check optimizations in here.
With that, we are roughly 1.5 seconds faster than the currently published version.

diff

**Review by dmtrKovalenko — APPROVED** [review]

**Pull request merged**
